[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
brick = "briKNc9rEPhJAowK2hN5CnkMmLEoopR9LBqfNVENVkL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rodri/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
